Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -8,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -44,35 +43,49 @@ jobs:
         run: |
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           
-          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-13-55-97-206.ap-southeast-2.compute.amazonaws.com << EOF
+          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-13-55-97-206.ap-southeast-2.compute.amazonaws.com << 'EOF'
+            
+            set -e 
 
-
-            sudo yum update -y
-            sudo yum install -y docker
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo yum update -y
+              sudo yum install -y docker
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed."
+            fi
+            
             docker --version
 
-
             sudo usermod -aG docker ec2-user
-            exit
-            su ec2-user
-            docker ps
-
+            newgrp docker
 
             DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
             mkdir -p $DOCKER_CONFIG/cli-plugins
             curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
             
             chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
-
             docker compose version
 
-            sudo yum install git -y
+            if ! command -v git &> /dev/null
+            then
+              echo "Git not found, installing..."
+              sudo yum install -y git
+            else
+              echo "Git is already installed."
+            fi
+
             git --version
 
-            mkdir Lab03
+            mkdir -p Lab03
             cd Lab03
-            git clone https://github.com/SewNguyenP2206/lab03.git
-
+            if [ ! -d "lab03" ]; then
+              git clone https://github.com/SewNguyenP2206/lab03.git
+            fi
+            
             cd lab03
             docker compose down
             docker compose build
